
version: '3'
services:
  ocastano-alpine:
    build: 
      context: .
      args:        
        DEVELOPER: ${USER}
    #environment:
    #  DEVELOPER: ${USER}
    container_name: ocastano-alpine
    volumes:
      - ./src:/app
    working_dir: /app
    user: ${USER}
    tty: true
